import "./globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

import { buttonVariants } from "@/components/ui/button";
import { aboutPath, createTicketPath, homePath, ticketsPath } from "@/paths";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${geistSans.className}`}>
      <body>
        <nav className="bg-gray-800 p-4">
          <ul className="flex justify-center space-x-4">
            <li>
              <Link
                href={homePath()}
                className={buttonVariants({
                  variant: "outline",
                  className: "min-w-40",
                })}
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                href={aboutPath()}
                className={buttonVariants({
                  variant: "outline",
                  className: "min-w-40",
                })}
              >
                About
              </Link>
            </li>
            <li>
              <Link
                href={ticketsPath()}
                className={buttonVariants({
                  variant: "outline",
                  className: "min-w-40",
                })}
              >
                Tickets
              </Link>
            </li>
            <li>
              <Link
                href={createTicketPath()}
                className={buttonVariants({
                  variant: "outline",
                  className: "min-w-40",
                })}
              >
                Create Ticket
              </Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
